import { test, expect } from '@playwright/test';

test('record, search, edit, history, trash, restore, and export through the browser', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: '今日の道しるべ' })).toBeVisible();
  await page.getByRole('button', { name: '新しい記録を作成', exact: true }).click();
  const form = page.getByRole('dialog');
  await form.getByLabel('種類').selectOption('knowledge');
  await form.getByLabel('タイトル', { exact: true }).fill('E2E 月の記憶');
  await form.getByLabel('本文', { exact: false }).fill('## 検証の知識\n\n**大切な記憶**を残す。\n\n- [ ] 読み返す');
  await form.getByRole('textbox', { name: /^タグ/ }).fill('検証, 月');
  await form.getByRole('button', { name: '記録する', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  await page.getByRole('button', { name: '記録を検索', exact: true }).click();
  await page.getByRole('dialog').getByRole('textbox').fill('E2E 月の記憶');
  await page.getByRole('dialog').getByRole('button', { name: /E2E 月の記憶/ }).click();
  await expect(page.getByRole('dialog').getByRole('heading', { name: '検証の知識' })).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: '編集', exact: true }).click();
  await page.getByRole('dialog').getByLabel('タイトル', { exact: true }).fill('E2E 月の記憶・更新');
  await page.getByRole('dialog').getByLabel('日付', { exact: true }).fill('2026-10-03');
  await page.getByRole('dialog').getByRole('button', { name: '変更を保存' }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'ナレッジ', exact: true }).click();
  await page.getByRole('button', { name: /E2E 月の記憶・更新/ }).click();
  await page.getByRole('dialog').getByRole('button', { name: '履歴', exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('button', { name: /第1版/ })).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: /第1版/ }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'この版に戻す', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: /E2E 月の記憶/ }).click();
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'E2E 月の記憶', exact: true })).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: '編集', exact: true }).click();
  await expect(page.getByRole('dialog').getByLabel('日付', { exact: true })).toHaveValue('');
  await page.getByRole('dialog').getByLabel('タイトル', { exact: true }).fill('E2E 月の記憶・更新');
  await page.getByRole('dialog').getByRole('button', { name: '変更を保存' }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: /E2E 月の記憶・更新/ }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'ゴミ箱へ', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'ゴミ箱', exact: true }).click();
  await page.getByRole('button', { name: 'E2E 月の記憶・更新を元に戻す', exact: true }).click();
  await page.getByRole('button', { name: 'ナレッジ', exact: true }).click();
  await expect(page.getByRole('button', { name: /E2E 月の記憶・更新/ })).toBeVisible();
  await page.getByRole('button', { name: '設定', exact: true }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: /書き出す/ }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe('odin-export.zip');
  expect(errors).toEqual([]);
});

test('mobile navigation, creation, completion and reduced motion remain usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/');
  await expect(page.getByRole('button', { name: '新しい記録を作成', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'その他の場所を開く' }).click();
  await page.getByRole('complementary', { name: 'メインメニュー' }).getByRole('button', { name: '買い物', exact: true }).click();
  await page.getByRole('button', { name: '新しい記録を作成', exact: true }).click();
  await page.getByRole('dialog').getByLabel('タイトル', { exact: true }).fill('E2E キッチンペーパー');
  await page.getByRole('dialog').getByRole('button', { name: '記録する', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'E2E キッチンペーパーを完了にする', exact: true }).click();
  await expect(page.getByRole('button', { name: 'E2E キッチンペーパーを未完了にする', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'E2E キッチンペーパーを未完了にする', exact: true }).click();
  await expect(page.getByRole('button', { name: 'E2E キッチンペーパーを完了にする', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '記録を検索', exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('textbox')).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
});

test('API rejects cross-site writes and stale updates', async ({ request }) => {
  const bad = await request.post('/api/entries', { headers: { Origin: 'https://unrelated.invalid' }, data: { title: 'blocked', kind: 'memo', body: '', tags: [] } });
  expect(bad.status()).toBe(403);
  const created = await request.post('/api/entries', { headers: { Origin: 'http://127.0.0.1:3100', 'Idempotency-Key': 'e2e-idempotency' }, data: { title: 'API revision check', kind: 'memo', body: '', tags: [] } });
  expect(created.status()).toBe(201);
  const { entry } = await created.json();
  const changed = await request.patch(`/api/entries/${entry.id}`, { headers: { Origin: 'http://127.0.0.1:3100' }, data: { title: 'updated', expectedRevision: entry.revision } });
  expect(changed.ok()).toBe(true);
  const conflict = await request.patch(`/api/entries/${entry.id}`, { headers: { Origin: 'http://127.0.0.1:3100' }, data: { title: 'stale', expectedRevision: entry.revision } });
  expect(conflict.status()).toBe(409);
  expect((await (await request.get(`/api/entries/${entry.id}`)).json()).entry.title).toBe('updated');
});

test('archived records stay searchable and notes link to their project', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: '新しい記録を作成', exact: true }).click();
  await page.getByRole('dialog').getByLabel('種類').selectOption('knowledge');
  await page.getByRole('dialog').getByLabel('タイトル', { exact: true }).fill('E2E プロジェクトの記憶');
  await page.getByRole('dialog').getByLabel('出典', { exact: false }).fill('https://example.com/source');
  await page.getByRole('dialog').getByRole('combobox', { name: 'プロジェクト', exact: true }).selectOption({ label: '新しいプロジェクト' });
  await page.getByRole('dialog').getByRole('button', { name: '記録する', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: /✦ 新しいプロジェクト/ }).click();
  await expect(page.getByRole('heading', { name: '関連する知識と着想' })).toBeVisible();
  await page.getByRole('button', { name: /E2E プロジェクトの記憶/ }).click();
  await expect(page.getByRole('dialog').getByRole('link', { name: /example.com\/source/ })).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: 'アーカイブ', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: '記録を検索', exact: true }).click();
  await page.getByRole('dialog').getByRole('textbox').fill('E2E プロジェクトの記憶');
  await expect(page.getByRole('dialog').getByRole('button', { name: /E2E プロジェクトの記憶.*アーカイブ/ })).toBeVisible();
});
